import { FC, ReactNode } from 'react';
import { useLocation, useNavigate, Link } from 'react-router-dom';
import { Breadcrumb, PageHeader, Typography } from 'antd';
import { ArrowLeftOutlined } from '@ant-design/icons';
import { neutralDarkPalette } from 'helpers';
import { BREADCRUMB_NAME_MAP } from 'helpers/constants';
import './Page.scss';

interface IPage {
  children: ReactNode;
  title: string;
}

const Page: FC<IPage> = ({ children, title }) => {
  const { pathname } = useLocation();
  const navigate = useNavigate();

  const lowerTitle = title.toLowerCase();

  const splitPaths = pathname.split('/').filter((p) => p);
  const autoGeneratedPathBreadcrumbs = splitPaths.map((path, index) => {
    const url = `/${splitPaths.slice(0, index + 1).join('/')}`;
    return (
      <Breadcrumb.Item key={url}>
        <Link to={url}>{BREADCRUMB_NAME_MAP?.[path]}</Link>
      </Breadcrumb.Item>
    );
  });

  const breadcrumbs = [
    <Breadcrumb.Item key="overview">
      <Link to="/">Overview</Link>
    </Breadcrumb.Item>,
    ...autoGeneratedPathBreadcrumbs,
  ];
  const pageBreadcrumb = (
    <Breadcrumb style={{ margin: '16px 0' }}>{breadcrumbs}</Breadcrumb>
  );

  const showBackButton = breadcrumbs.length > 1;

  const PageTitle = (
    <Typography.Title style={{ marginBottom: '0.1em' }}>
      {title}
    </Typography.Title>
  );

  return (
    <div
      className={`page ${lowerTitle}`}
      style={{ backgroundColor: neutralDarkPalette?.[2] }}
    >
      <header className={`page__header ${lowerTitle}__header`}>
        <PageHeader
          title={PageTitle}
          backIcon={
            showBackButton ? (
              <ArrowLeftOutlined style={{ fontSize: '24px' }} />
            ) : null
          }
          breadcrumb={pageBreadcrumb}
          style={{ backgroundColor: neutralDarkPalette?.[7] }}
          onBack={(): false | void => showBackButton && navigate(-1)}
        />
      </header>
      <section className={`page__content ${lowerTitle}__content`}>
        {children}
      </section>
      <footer className={`page__footer ${lowerTitle}__footer`}>Footer</footer>
    </div>
  );
};

export default Page;
